name: crop_compass
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: fredoka
      fonts:
        - asset: assets/fonts/Fredoka_Condensed-SemiBold.ttf
